apiVersion: apps/v1
kind: Deployment
metadata:
 name: "dp-{{ .Chart.Name }}"
 labels:
  app: dp-gitlabhelm
spec:
 selector:
  matchLabels:
   app: gitlabhelm
 replicas: 1
 template:
  metadata:
   labels:
    app: gitlabhelm
  spec:
   containers:
   - name: {{ .Chart.Name }}
     image: gitlab/gitlab-ce
     securityContext:
      privileged: true
     volumeMounts:
     - name: config
       mountPath: /etc/gitlab
     - name: data
       mountPath: /var/opt/gitlab
     - name: logs
       mountPath: /var/log/gitlab
     ports:
     - name: web
       containerPort: 80
     - name: ssl
       containerPort: 443
     - name: ssh
       containerPort: 22
   imagePullSecrets:
   - name: docker-registry-login
   restartPolicy: Always
   volumes:
   - name: config
     persistentVolumeClaim:
      claimName: "{{ .Values.pv.name }}-pvc-config"
   - name: data
     persistentVolumeClaim:
      claimName: "{{ .Values.pv.name }}-pvc-data"
   - name: logs
     persistentVolumeClaim:
      claimName: "{{ .Values.pv.name }}-pvc-log"
   
