kind: PersistentVolume
apiVersion: v1
metadata:
  name: "{{.values.pv.name}}-log"
  labels:
    type: local
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{.values.pv.log}}
