kind: PersistentVolume
apiVersion: v1
metadata:
  name: "{{.Values.pv.name}}-data"
  labels:
    type: local
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{.Values.pv.data}}
