apiVersion: v1
kind: Service
metadata:
 name: "svc-{{.Chart.Name}}"
 labels:
  app: gitlabhelm
spec:
 type: NodePort
 ports:
 - name: web
   targetPort: {{ .Values.service.ports.web }}
   port: {{ .Values.service.ports.web }}
 - name: ssh
   targetPort: {{ .Values.service.ports.ssh }}
   port: {{ .Values.service.ports.ssh }}
 - name: ssl
   targetPort: {{ .Values.service.ports.ssl }}
   port: {{ .Values.service.ports.ssl }}
 selector:
  app: gitlabhelm
  
