version: '3' 
services: 
  app: 
    build: . 
    image: docker.jointree.co.kr/jointree/jointestflask
  production:
    image: docker.jointree.co.kr/jointree/jointestflask:${BUILD_NUMBER}
    command: python app.py 
    volumes: 
    - .:/code 
    ports: 
    - "80:80"