apiVersion: v1
kind: Pod
metadata:
  name: join-hue
  labels:
    test: ambari
    tests: jts
spec:
  containers:
  - image: docker.jointree.co.kr/jointree/joinhue:v1.0
    name: hue
    env:
    - name: JAVA_HOME
      value: "/usr/lib/jvm/java-1.8.0-openjdk/"
    envFrom:
     - configMapRef:
        name: server-cfg
    volumeMounts:
      - name: csv-conn
        mountPath: /csv
    securityContext:
     privileged: true
    ports:
    - name: sshd
      containerPort: 22
    - name: ambariport
      containerPort: 8888
  - image: postgres:12
    name: post
    envFrom:
     - configMapRef:
        name: ampost
    ports:
    - containerPort: 5432
      name: postdb
  restartPolicy: Always
  imagePullSecrets:
   - name: docker-registry-login
  nodeSelector:
   kubernetes.io/hostname: jointree-poweredge-r740
  volumes:
    - name: csv-conn
      persistentVolumeClaim:
        claimName: csvconn
