apiVersion: v1
kind: Pod
metadata:
  name: nn1
  labels:
    test: ambari
    tests: jts
spec:
  hostname: nn1
  subdomain: jts2
  setHostnameAsFQDN: true
  containers:
  - image: docker.jointree.co.kr/jointree/joinambari:v2.0
    name: ambariserver
    command: ["/bin/bash","-c","mkdir -p /csv"]
    env:
    - name: JAVA_HOME
      value: "/usr/lib/jvm/java-1.8.0-openjdk"
    envFrom:
     - configMapRef:
        name: server-cfg
    volumeMounts:
      - name: csv-conn
        mountPath: /csv
    securityContext:
     privileged: true
    ports:
    - name: sshd
      containerPort: 22
    - name: ambariport
      containerPort: 8080
  - image: postgres:12
    name: post
    envFrom:
     - configMapRef:
        name: ampost
    ports:
    - containerPort: 5432
      name: postdb
  restartPolicy: Always
  imagePullSecrets:
   - name: docker-registry-login
  volumes:
    - name: csv-conn
      persistentVolumeClaim:
        claimName: csvconn
