kind: Service
apiVersion: v1
metadata:
  name: svc_firefox
  labels:
    type: svc_tools
    app: svc_firefox
spec:
  ports:
    - name: filezilla
      protocol: TCP
      port: 5800
      targetPort: 5800
      nodePort: 30125
  selector:
    type: tools
    app: firefox
  type: NodePort