kind: Service
apiVersion: v1
metadata:
  name: svc-putty
  labels:
    type: svc-tools
    app: svc-putty
spec:
  ports:
    - name: putty
      protocol: TCP
      port: 5800
      targetPort: 5800
      nodePort: 32127
  selector:
    type: tools
    app: putty
  type: NodePort
