apiVersion: v1
kind: Service
metadata:
 name: "{{.Chart.Name}}-service"
 labels: 
  app : {{ .Chart.Name }}
spec:
 type: {{ .Values.service.type}}
 ports:
 - name:  testport
   port:  80
   targetPort: 80
   nodePort: {{.Values.service.nodePort}}
 selector:
  app: {{.Chart.Name}}
